<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, inital-scale=1.0">
    <link href="../css/bootstrap.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="../css/main.css">
        
    <title>Contact Us - Snap!</title>
</head>
<body>
    <div id="main-wrapper">
        <header>
            <a href="../index.php"><img src="../images/logo.png" alt="Snap!" width="451" height="151" id="logo"></a>
            
            <div id="nav">
                <a href="../index.php">Home</a> | 
                <a href="../register.php">Sign Up</a> | 
                <a href="#">Profile</a> | 
                <a href="http://www.flickr.com/">Flickr</a>
            </div>
        </header>
        
        <div id="contact">
            <h2>
                <b>Name:</b> Megan Zimmerman<br>
                <b>E-mail:</b> zimmemeg@fullsail.edu<br>
                Developed for educational purposes for Full Sail University.
            </h2>
        </div>
        
    </div>
</body>
<footer>
    Megan Zimmerman | MDD 1309 | API use from <a href="http://www.flickr.com/">Flickr</a> | <a href="Views/contact.inc">Contact Us</a>
</footer>
</html>
